openapi: 3.0.0
info:
  title: Generations API
  version: "1.0"
  description: API do zarządzania generowaniem fiszek przez AI

paths:
  /api/v1/generations:
    get:
      summary: Pobierz listę zadań generacji
      description: |
        Zwraca paginowaną listę zadań generacji fiszek dla zalogowanego użytkownika.
        Zadania są sortowane od najnowszych do najstarszych.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Numer strony (domyślnie 1)
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Liczba elementów na stronę (domyślnie 20, max 100)
      responses:
        "200":
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - pagination
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/GenerationTaskVM"
                  pagination:
                    $ref: "#/components/schemas/PaginationMeta"
        "400":
          description: Nieprawidłowe parametry paginacji
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Błąd serwera
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    GenerationTaskVM:
      type: object
      required:
        - id
        - status
        - createdAt
        - modelUsed
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: string
          enum: [pending, processing, completed, failed, cancelled]
          example: "completed"
        createdAt:
          type: string
          format: date-time
          example: "2024-03-14T12:00:00Z"
        modelUsed:
          type: string
          example: "openrouter/opus-mixtral-8x22b"
        progress:
          type: number
          minimum: 0
          maximum: 100
          example: 45
          nullable: true

    PaginationMeta:
      type: object
      required:
        - page
        - limit
        - totalPages
        - totalItems
      properties:
        page:
          type: integer
          minimum: 1
          example: 1
        limit:
          type: integer
          minimum: 1
          maximum: 100
          example: 20
        totalPages:
          type: integer
          minimum: 0
          example: 5
        totalItems:
          type: integer
          minimum: 0
          example: 100

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              example: "400"
            message:
              type: string
              example: "Invalid pagination parameters"
            details:
              type: object
              description: Dodatkowe szczegóły błędu (opcjonalne)
